function createfigure_SDH_SCAS_SLC25A10(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of semilogy x data
%  YMATRIX1:  matrix of semilogy y data

%  Auto-generated by MATLAB on 25-Sep-2025 16:18:21

% Create figure
figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'LineWidth',2);
set(semilogy1(1),'DisplayName','J_{tot}');
set(semilogy1(2),'DisplayName','J_{SDH}');
set(semilogy1(3),'DisplayName','J_{SCAS}');

% Create ylabel
ylabel('Flux (\mumol/min/g)','FontWeight','bold');

% Create xlabel
xlabel('Time (min)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.38117451150805 350.109092218028]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);

grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',30,'FontWeight','bold','YMinorTick','on','YScale',...
    'log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.757616974972797 0.664298713904392 0.134385201305767 0.244479495268139],...
    'FontSize',30);

