function createfigure(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5, YMatrix6)
%CREATEFIGURE(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5, YMatrix6)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  YMATRIX2:  matrix of plot y data
%  YMATRIX3:  matrix of plot y data
%  YMATRIX4:  matrix of plot y data
%  YMATRIX5:  matrix of plot y data
%  YMATRIX6:  matrix of plot y data

%  Auto-generated by MATLAB on 25-Sep-2025 10:30:56

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Position',...
    [0.131725417439703 0.745323741007194 0.320037105751392 0.220143884892086]);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','J_{succ} (\mumol/min/g)');
set(plot1(2),'DisplayName','J_{pho} (\mumol/min/g)');

% Create ylabel
ylabel({'Flux','(\mumol/min/g)',''},'FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);

grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.265219294233226 0.876517342147519 0.18391959798995 0.0867952522255192],...
    'FontSize',16);

% Create axes
axes2 = axes('Position',...
    [0.61317254174397 0.746762589928058 0.329313543599258 0.218705035971223]);
hold(axes2,'on');

% Create multiple line objects using matrix input to plot
plot2 = plot(X1,YMatrix2,'LineWidth',2,'Color',[0 0 0]);
set(plot2(1),'DisplayName','\Delta G');
set(plot2(2),'DisplayName','\Delta G = 0 (Equilibrium)','LineStyle','--');

% Create ylabel
ylabel({'\Delta G ','(kJ/mol)'},'FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 4]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[-1 1]);

grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontSize',24,'FontWeight','bold');
% Create legend
legend2 = legend(axes2,'show');
set(legend2,...
    'Position',[0.724497889493852 0.887626886621267 0.220603015075377 0.0719584569732938],...
    'FontSize',18);

% Create axes
axes3 = axes('Position',...
    [0.131725417439703 0.42589928057554 0.319109461966605 0.21294964028777]);
hold(axes3,'on');

% Create multiple line objects using matrix input to plot
plot3 = plot(X1,YMatrix3,'Color',[0 0 1]);
set(plot3(1),'DisplayName','Simulated','LineWidth',2);
set(plot3(2),'DisplayName','Analytically Derived Equilibrium',...
    'LineWidth',1.5,...
    'LineStyle','--');

% Create ylabel
ylabel('[S_m] (mM)','FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[9.8 10]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes3,[-1 1]);

grid(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'FontSize',24,'FontWeight','bold');
% Create legend
legend3 = legend(axes3,'show');
set(legend3,...
    'Position',[0.153813132413083 0.563136381636753 0.304623735130732 0.0707715130701263],...
    'Interpreter','latex',...
    'FontSize',18);

% Create axes
axes4 = axes('Position',...
    [0.615795454545455 0.424460431654676 0.326690630797773 0.214388489208633]);
hold(axes4,'on');

% Create multiple line objects using matrix input to plot
plot4 = plot(X1,YMatrix4,'Color',[1 0 0]);
set(plot4(1),'DisplayName','Simulated','LineWidth',2);
set(plot4(2),'DisplayName','Analytically Derived Equilibrium',...
    'LineWidth',1.5,...
    'LineStyle','--');

% Create ylabel
ylabel('[S_{ims}] (mM)','FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0.1 0.3]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes4,[-1 1]);

grid(axes4,'on');
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'FontSize',24,'FontWeight','bold');
% Create legend
legend4 = legend(axes4,'show');
set(legend4,...
    'Position',[0.646181286404265 0.428283308213138 0.304623735130732 0.0707715130701263],...
    'Interpreter','latex',...
    'FontSize',18);

% Create axes
axes5 = axes('Position',...
    [0.131725417439703 0.0946273262847343 0.317254174397032 0.217602889542604]);
hold(axes5,'on');

% Create multiple line objects using matrix input to plot
plot5 = plot(X1,YMatrix5,'Color',[0 1 0]);
set(plot5(1),'DisplayName','Simulated','LineWidth',2);
set(plot5(2),'DisplayName','Analytically Derived Equilibrium',...
    'LineWidth',1.5,...
    'LineStyle','--');

% Create ylabel
ylabel('[P_m] (mM)','FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[10 10.2]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes5,[-1 1]);

grid(axes5,'on');
hold(axes5,'off');
% Set the remaining axes properties
set(axes5,'FontSize',24,'FontWeight','bold');
% Create legend
legend5 = legend(axes5,'show');
set(legend5,...
    'Position',[0.15248188629193 0.101052364077768 0.304623735130732 0.0707715130701263],...
    'Interpreter','latex',...
    'FontSize',18);

% Create axes
axes6 = axes('Position',...
    [0.616723098330241 0.0956115107913669 0.325762987012987 0.213741007194245]);
hold(axes6,'on');

% Create multiple line objects using matrix input to plot
plot6 = plot(X1,YMatrix6,'Color',[1 0 1]);
set(plot6(1),'DisplayName','Simulated','LineWidth',2);
set(plot6(2),'DisplayName','Analytically Derived Equilibrium',...
    'LineWidth',1.5,...
    'LineStyle','--');

% Create ylabel
ylabel('[P_{ims}] (mM)','FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0.3 0.5]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes6,[-1 1]);

grid(axes6,'on');
hold(axes6,'off');
% Set the remaining axes properties
set(axes6,'FontSize',24,'FontWeight','bold');
% Create legend
legend6 = legend(axes6,'show');
set(legend6,...
    'Position',[0.645657244955845 0.233481149939757 0.304623735130732 0.0707715130701263],...
    'Interpreter','latex',...
    'FontSize',18);

% Create textbox
annotation(figure1,'textbox',...
    [0.00357462019660405 0.298913043478259 0.0436553399281587 0.0628586956521724],...
    'String','e)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.497887988772126 0.29891304347826 0.0436553399281587 0.0581579824036887],...
    'String','f)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.00357462019660407 0.624999999999998 0.0436553399281587 0.0628586956521725],...
    'String','c)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.495207023624673 0.626358695652173 0.0436553399281587 0.0581579824036887],...
    'String','d)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.490738748378918 0.947010869565218 0.0436553399281588 0.0581579824036889],...
    'String','b)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.00175332136266661 0.949888567406944 0.0436553399281587 0.0628586956521725],...
    'String','a)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

