function createfigure(X1, Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data
%  Y3:  vector of plot y data
%  Y4:  vector of plot y data
%  Y5:  vector of plot y data
%  Y6:  vector of plot y data
%  Y7:  vector of plot y data
%  Y8:  vector of plot y data
%  Y9:  vector of plot y data

%  Auto-generated by MATLAB on 16-Aug-2025 23:08:22

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Position',...
    [0.104560357388667 0.751020408163265 0.201116379556221 0.208521702239024]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('[M_m] (mM)','FontWeight','bold','FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[10 10.2812144472939]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
% box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',20,'FontWeight','bold');
% Create axes
axes2 = axes('Position',...
    [0.428121881589727 0.751020408163265 0.200665997198152 0.2086000069422]);
hold(axes2,'on');

% Create plot
plot(X1,Y2,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('[M_{ims}] (mM)','FontWeight','bold','FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.6 0.907726454875752]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[-1 1]);
% box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontSize',20,'FontWeight','bold');
% Create axes
axes3 = axes('Position',...
    [0.754276866108683 0.753741496598639 0.206032911238849 0.204518374289142]);
hold(axes3,'on');

% Create plot
plot(X1,Y3,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel({'[M_m]/[M_{ims}]'},'FontWeight','bold',...
    'FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[10 16.4102432561139]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes3,[-1 1]);
% box(axes3,'on');
grid(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'FontSize',20,'FontWeight','bold');
% Create axes
axes4 = axes('Position',...
    [0.101710492064814 0.414965986394557 0.206984604384397 0.213553373180783]);
hold(axes4,'on');

% Create plot
plot(X1,Y4,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('[S_m] (mM)','FontWeight','bold','FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[9.87271917474482 10]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes4,[-1 1]);
% box(axes4,'on');
grid(axes4,'on');
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'FontSize',20,'FontWeight','bold');
% Create axes
axes5 = axes('Position',...
    [0.427879961277832 0.412244897959183 0.203072419674549 0.216326530612245]);
hold(axes5,'on');

% Create plot
plot(X1,Y5,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('[S_{ims}] (mM)','FontWeight','bold','FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0.5 0.627280825255177]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes5,[-1 1]);
% box(axes5,'on');
grid(axes5,'on');
hold(axes5,'off');
% Set the remaining axes properties
set(axes5,'FontSize',20,'FontWeight','bold');
% Create axes
axes6 = axes('Position',...
    [0.755893671220626 0.414965986394557 0.20344805191587 0.214992222101645]);
hold(axes6,'on');

% Create plot
plot(X1,Y6,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel({'[S_m]/[S_{ims}]'},'FontWeight','bold',...
    'FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[15 20]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes6,[-1 1]);
% box(axes6,'on');
grid(axes6,'on');
hold(axes6,'off');
% Set the remaining axes properties
set(axes6,'FontSize',20,'FontWeight','bold');
% Create axes
axes7 = axes('Position',...
    [0.101181540287826 0.0775510204081631 0.209424520318235 0.23056566641001]);
hold(axes7,'on');

% Create plot
plot(X1,Y7,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('[P_m] (mM)','FontWeight','bold','FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[9.8 10]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes7,[-1 1]);
% box(axes7,'on');
grid(axes7,'on');
hold(axes7,'off');
% Set the remaining axes properties
set(axes7,'FontSize',20,'FontWeight','bold');
% Create axes
axes8 = axes('Position',...
    [0.431278973071768 0.0748299319727891 0.200860426734621 0.218252300920368]);
hold(axes8,'on');

% Create plot
plot(X1,Y8,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('[P_{ims}] (mM)','FontWeight','bold','FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes8,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes8,[0.5 0.7]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes8,[-1 1]);
% box(axes8,'on');
grid(axes8,'on');
hold(axes8,'off');
% Set the remaining axes properties
set(axes8,'FontSize',20,'FontWeight','bold');
% Create axes
axes9 = axes('Position',...
    [0.755957531882659 0.0802721088435374 0.204352245464873 0.216891756702681]);
hold(axes9,'on');

% Create plot
plot(X1,Y9,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel({'[P_m]/[P_{ims}]'},'FontWeight','bold',...
    'FontSize',22);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',22);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes9,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes9,[14.2016602808972 20]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes9,[-1 1]);
% box(axes9,'on');
grid(axes9,'on');
hold(axes9,'off');
% Set the remaining axes properties
set(axes9,'FontSize',20,'FontWeight','bold');
% Create textbox
annotation(figure1,'textbox',...
    [0.00299401197604789 0.942522372737262 0.0602968460111317 0.0676258992805756],...
    'String',{'a)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.324920343243812 0.946604005390325 0.0612244897959184 0.0676258992805756],...
    'String',{'b)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [2.99497809800961e-05 0.624701063611605 0.0612244897959184 0.0676258992805755],...
    'String',{'d)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.329700714737029 0.623340519393919 0.0602968460111317 0.0676258992805755],...
    'String',{'e)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.00208585732697236 0.29607275610131 0.0612244897959184 0.0676258992805756],...
    'String',{'g)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.329243739046587 0.289270035012875 0.0602968460111317 0.0676258992805756],...
    'String',{'h)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.650209745079055 0.626666799738832 0.0528756957328386 0.0676258992805755],...
    'String',{'f)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.649301590429981 0.945734895204444 0.0602968460111317 0.0676258992805756],...
    'String',{'c)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.651605791321515 0.283827858142125 0.0510204081632653 0.0676258992805756],...
    'String',{'i)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

end
