function createfigure(YData1, XData1, YData2, X1, YMatrix1, X2, Y1)
%CREATEFIGURE(YData1, XData1, YData2, X1, YMatrix1, X2, Y1)
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  YDATA2:  patch ydata
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 16-Aug-2025 23:23:04

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Position',...
    [0.125692980787522 0.123499142367067 0.436224462621266 0.819689252754421]);
hold(axes1,'on');

% Create patch
patch('DisplayName','Influx Region','YData',YData1,'XData',XData1,...
    'FaceAlpha',0.1,...
    'FaceColor',[1 0 0],...
    'EdgeColor','none');

% Create patch
patch('DisplayName','Efflux Region','YData',YData2,'XData',XData1,...
    'FaceAlpha',0.1,...
    'FaceColor',[0 0.447058826684952 0.74117648601532],...
    'EdgeColor','none');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3);
set(plot1(1),'DisplayName','J_{succ}');
set(plot1(2),'DisplayName','J_{mal}');
set(plot1(3),'DisplayName','J_{pho}');

% Create ylabel
ylabel({'Flux ','(\mumol/min/g)'},'FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-4.5 5.5]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
%box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.383586448477889 0.676909100783098 0.124305555555556 0.225503355704698],...
    'FontSize',21.6);

% Create axes
axes2 = axes('Position',...
    [0.68216935622885 0.121783876500858 0.307179756197185 0.819473937975457]);
hold(axes2,'on');

% Create plot
plot(X2,Y1,'DisplayName','J_{tot}','LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel({'Flux ','(\mumol/min/g)'},'FontWeight','bold','FontSize',26.4);

% Create xlabel
xlabel('Time (min)','FontWeight','bold','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 10]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[-1 1]);
%box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontSize',24,'FontWeight','bold');
% Create legend
legend2 = legend(axes2,'show');
set(legend2,'FontSize',21.6);

% Create textbox
annotation(figure1,'textbox',...
    [0.00262315605475437 0.952946852387097 0.0451388888888889 0.0630872483221476],...
    'String',{'a)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.573037357238186 0.952946852387097 0.0458333333333333 0.0630872483221476],...
    'String',{'b)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'EdgeColor','none');

end
